# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://182.92.217.138:3306/exchange?rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: ewdsG87few

# Logger Config
logging:
  level:
    com.kingmao.mybatisplus: debug