# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://182.92.217.138:3306/exchange?rewriteBatchedStatements=true&autoReconnect=true
    username: yiqinxuan
    password: Lzslov123!

# Logger Config
logging:
  level:
    com.kingmao.mybatisplus: debug