# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/exchange?rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: 123456

# Logger Config
logging:
  level:
    com.kingmao.mybatisplus: debug